# Generated by Django 6.0.2 on 2026-04-17 02:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('tiempo_segundos', models.IntegerField(blank=True, null=True)),
                ('url_video', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('Paciente', 'Paciente'), ('Terapeuta', 'Terapeuta'), ('Admin', 'Admin')], default='Paciente', max_length=20)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('facebook_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='PerfilClinico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnostico_principal', models.CharField(max_length=255)),
                ('historial_medico', models.TextField()),
                ('nivel_movilidad', models.CharField(choices=[('1', 'Nivel 1 - Muy Limitado'), ('2', 'Nivel 2 - Limitado'), ('3', 'Nivel 3 - Moderado'), ('4', 'Nivel 4 - Autónomo')], max_length=20)),
                ('restricciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel_dificultad', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_terapeuta', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.CharField(max_length=255)),
                ('numero_licencia', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=255)),
                ('entidad_afectada', models.CharField(max_length=100)),
                ('entidad_id', models.UUIDField()),
                ('datos_previos', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionRutina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Asignada', 'Asignada'), ('En progreso', 'En progreso'), ('Completada', 'Completada')], default='Asignada', max_length=20)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RehabWeb_API.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='SesionDeRehabilitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_completada', models.DateTimeField()),
                ('duracion_minutos', models.IntegerField()),
                ('percepcion_esfuerzo', models.IntegerField()),
                ('feedback_paciente', models.TextField(blank=True, null=True)),
                ('asignacion_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='RehabWeb_API.asignacionrutina')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_paciente', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('estrategia_validacion', models.CharField(max_length=100)),
                ('estrategia_progreso', models.CharField(max_length=100)),
                ('perfil_clinico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RehabWeb_API.perfilclinico')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='RehabWeb_API.terapeuta')),
            ],
        ),
        migrations.AddField(
            model_name='asignacionrutina',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='RehabWeb_API.paciente'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='terapeuta_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_creadas', to='RehabWeb_API.terapeuta'),
        ),
        migrations.CreateModel(
            name='EvaluacionClinica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_evaluacion', models.DateTimeField()),
                ('notas_evaluacion', models.TextField()),
                ('metricas_objetivas', models.JSONField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='RehabWeb_API.paciente')),
                ('terapeuta_evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RehabWeb_API.terapeuta')),
            ],
        ),
        migrations.AddField(
            model_name='asignacionrutina',
            name='terapeuta_asignador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RehabWeb_API.terapeuta'),
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RehabWeb_API.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_asociados', to='RehabWeb_API.rutina')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('rutina', 'ejercicio')},
            },
        ),
    ]
