# Generated by Django 6.0.2 on 2026-04-17 05:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RehabWeb_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='estado_publicacion',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_VALIDACION', 'Pendiente de Validación'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=25),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='evidencia_cientifica',
            field=models.TextField(blank=True, help_text='Soporta Markdown o HTML enriquecido', null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='referencias_bibliograficas',
            field=models.JSONField(blank=True, default=list, help_text="Lista de {tipo: 'link'|'pdf', url: string, titulo: string}", null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='video_archivo',
            field=models.FileField(blank=True, null=True, upload_to='ejercicios/videos/'),
        ),
        migrations.CreateModel(
            name='ValidacionEjercicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_valido', models.BooleanField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='RehabWeb_API.ejercicio')),
                ('validador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validación de Ejercicio',
                'verbose_name_plural': 'Validaciones de Ejercicios',
                'unique_together': {('ejercicio', 'validador')},
            },
        ),
    ]
